/**
 * THE DESCENT SCREEN — shown while the next floor is built.
 *
 * ── THE ONE THING THIS SCREEN MUST NOT DO ──
 * Stall. It exists because building a floor blocks the GPU, and its entire job
 * is to be on screen DURING that block. That makes it the one place in this
 * migration where "the UI is painted from the render loop" is a hazard rather
 * than a convenience: if the loop is stalled, a painted screen freezes with it,
 * whereas the DOM version was composited by the browser and kept animating.
 *
 * So the bar is driven by WALL CLOCK, not by frames. When the loop stutters the
 * bar jumps to where it should be rather than pausing mid-sweep — a bar that
 * stops moving reads as a hang, which is exactly the impression this screen
 * exists to prevent. `descent bar stall is one compile` is a lesson this repo
 * has already paid for once.
 *
 * ── AND THE COROLLARY: IT MUST BE CHEAP ──
 * Every millisecond this screen spends painting is a millisecond taken from the
 * work it is covering. The labyrinth behind the plate is therefore PRE-RENDERED
 * into two opaque canvases (`loading-maze.ts`) and a frame blits them; only the
 * light front, the thread, the torches and the motes are drawn per frame.
 *
 * The version this replaced walked every cell of the field every frame —
 * ~2,400 `fillRect`s each preceded by a freshly built `rgba(...)` string — and
 * the painful part is that the result was invisible: those translucent fills
 * landed nearest VOID under the pass's palette snap, so the most expensive
 * thing on the screen contributed nothing you could see. Measure a loading
 * screen's paint like any other hot loop; this one runs while the budget is
 * already spent.
 *
 * ── WHY THE MAZE ON SCREEN IS NOT THE REAL ONE ──
 * It would be easy to draw `state.grid` here — the floor is fully generated by
 * the time the bar is moving, and `map-render.ts` already knows how. It would
 * also hand the player the finished map of a floor they are about to explore,
 * which is the exact spoiler the fog exists to prevent (`startLevel` resets fog
 * every descent for this reason). So this grows its OWN throwaway labyrinth in
 * the same visual language — torchlit stone, a gold route through it — and the
 * player learns nothing from studying it.
 *
 * The first canvas port of this screen dropped the labyrinth, the caption, the
 * divider and the percentage, keeping only a title and a bar on a flat black
 * field. That was not a stylistic simplification: the screen had nothing left
 * on it, which on the one screen whose whole job is to say "something is
 * happening" is the worst available failure. All of it is back.
 */
import { UI, GRID, C } from "../theme";
import { bar, bevel, fillRect, rect, strokeRect, text, type UiFrame } from "../im";
import { close, push, type UiScreen } from "../stack";
import { ghostFloorLabel } from "../../dev/ghost-maze";
import { paintMazeArt, type MazeArt } from "./loading-maze";

/**
 * The SAME contract `floor-loading.ts` publishes, so the two are drop-in
 * interchangeable and the caller never learns which one it got.
 *
 * `phase()` NEVER goes backwards — the DOM version clamped that and it matters:
 * a bar that retreats mid-descent reads as the load having failed and restarted.
 */
export interface FloorLoading {
  phase(label: string, frac: number): void;
  close(): void;
}

/**
 * The box this screen is authored for — see `UiScreen.design`.
 *
 * Deliberately the smallest in the game. There are four lines on it and no
 * lists, so it can afford the largest zoom the grid allows, and it is the one
 * screen a player stares at with nothing else to do. On a 1600x900 grid this
 * resolves to 3x: depth numerals 72 texels tall instead of 24.
 */
export const DESIGN = { w: 480, h: 270, max: 3 };

/**
 * Labyrinth cell size, in UI pixels.
 *
 * Chosen for READABILITY as a maze rather than as texture: at 18 UI pixels a
 * 1600x900 grid holds a field about 33 cells across, which is big enough that
 * the eye follows a corridor and small enough that the walls still fill the
 * screen. The old 8px cell gave 70-odd columns of one-cell corridors, which at
 * a glance is gravel rather than a maze.
 */
const CELL_UI = 18;

/** The light front, and the thread that runs ahead of it. */
const FRONT_CORE = C(17); // flame light — the leading edge itself
const FRONT_WARM = C(15); // flame dark — the warmth trailing it
const THREAD_GLOW = C(14); // ember — the route's wide underlayer
const THREAD_CORE = C(16); // flame — the route
const SPARK = C(18); // flame core — the head, and a torch at its brightest
const MOTE = C(15);

interface LoadState {
  level: number;
  progress: number;
  label: string;
  startedAt: number;
  /** Device-pixel size the art was painted for; 0 until the first paint. */
  artW: number;
  artH: number;
  art: MazeArt | null;
}

let live: LoadState | null = null;

export function isFloorLoadingOpen(): boolean {
  return live !== null;
}

/**
 * Paint the labyrinth on the FIRST PAINT, and again only if the frame changes
 * size.
 *
 * Not at `open()`: the caller is the descent path, which knows the floor number
 * and nothing about how big the frame is. The frame size (and therefore the
 * zoom, and therefore the pixel size of a cell) is first knowable inside
 * `paint`.
 *
 * The one-off cost is two opaque canvases and a few thousand `fillRect`s, paid
 * on the frame the screen first appears — which is the frame BEFORE the floor
 * build blocks the thread, and is the cheap moment to pay it. It is not even an
 * added cost: measured against the screen this replaced (which grew a labyrinth
 * of its own on first paint), the whole first frame went from ~28ms to ~18ms.
 */
function ensureArt(s: LoadState, f: UiFrame): void {
  // Device pixels, not UI units: the backdrop is blitted 1:1 under an identity
  // transform (see `paintBackdrop`), so it must be painted in the pixel grid's
  // own units. The extra cell of width is slack for the `floor()` in the
  // frame's size — without it a fractional zoom leaves a black strip down the
  // right-hand edge.
  const w = Math.ceil(f.w * f.scale) + Math.ceil(f.scale);
  const h = Math.ceil(f.h * f.scale) + Math.ceil(f.scale);
  if (w === s.artW && h === s.artH && s.art) return;
  s.artW = w;
  s.artH = h;
  s.art = paintMazeArt(w, h, Math.round(CELL_UI * f.scale));
}

/**
 * THE BACKDROP — cold labyrinth, torchlit behind the front, one route through.
 *
 * Everything here is drawn under the IDENTITY transform, in device pixels. The
 * screen's own widgets are laid out in zoomed UI units (2.7x at 1600x900) and a
 * blit through that transform would resample the whole field: with smoothing
 * off, a 2px wall becomes an alternating 5px/6px line, and the labyrinth's
 * strokes visibly change weight as they cross the screen. So the transform is
 * saved, reset, and restored around the lot.
 *
 * The whole field is laid out from the first frame in cold stone, and the sweep
 * LIGHTS it left to right. Revealing the walls themselves instead left half the
 * screen empty for half the descent, which reads as "nothing is happening" —
 * the opposite of what a loading screen is for.
 */
function paintBackdrop(f: UiFrame, art: MazeArt, frac: number, t: number): void {
  const g = f.g;
  g.save();
  g.setTransform(1, 0, 0, 1, 0, 0);
  g.imageSmoothingEnabled = false;

  // The front starts one cell off-screen so the first frame is honestly dark,
  // and ends one cell past the right edge so the last frame is fully lit.
  const edge = Math.max(0, Math.min(art.w, Math.round(frac * (art.w + art.cell * 2)) - art.cell));

  // Two WHOLE-layer blits, cold then lit-over-the-left, and not the obvious
  // saving of a source-rect slice each. The slices copy one screen per frame
  // where this copies about one and a half — and over three interleaved A/B
  // runs against the old screen they came out ~15% SLOWER, not faster: a
  // cropped `drawImage` leaves the plain blit path. (Measured in the
  // node-canvas harness, which is the only 2D backend this repo can time
  // without a browser; the point stands that the "obvious" saving was not one.)
  g.drawImage(art.cold, 0, 0);

  if (edge > 0) {
    // ONE clip for everything the torchlight owns: the lit stone, the torches
    // in it, the embers over it and the route through it.
    //
    // The route matters most here. It advances by DISTANCE ALONG ITSELF while
    // the front advances by COLUMN, and a maze route doubles back — so the
    // thread regularly runs ahead of the light and, unclipped, painted a length
    // of gold in the pitch dark two thirds of the way across the screen. It
    // read as a bug, and it is also a lie: the route through a stretch the
    // torch has not reached is not something the screen should claim to know.
    // Clipped, the thread simply meets the front and waits there, which is both
    // honest and the better picture.
    g.save();
    g.beginPath();
    g.rect(0, 0, edge, art.h);
    g.clip();
    g.drawImage(art.lit, 0, 0);
    paintThread(g, art, frac);
    paintTorches(g, art, edge, t);
    paintMotes(g, art, edge, t);
    g.restore();
  }

  // The leading edge, as a torch-warm line, drawn LAST so the thread appears to
  // arrive at it. Two flat bars rather than a gradient: a ramp here would be
  // quantized to the same two entries anyway, and the hard edge is what makes
  // it read as light ARRIVING.
  if (edge > 0 && edge < art.w) {
    g.fillStyle = FRONT_WARM;
    g.fillRect(edge - 6, 0, 6, art.h);
    g.fillStyle = FRONT_CORE;
    g.fillRect(edge - 2, 0, 2, art.h);
  }

  g.restore();
}

/**
 * The flicker on every torch the light has already reached.
 *
 * The sconce and its halo are baked into the lit layer; this adds only the part
 * that moves. One `fillRect` per lit torch — a couple of dozen at most, which is
 * the entire animation budget this screen can afford to spend on decoration.
 */
function paintTorches(g: CanvasRenderingContext2D, art: MazeArt, edge: number, t: number): void {
  for (let i = 0; i < art.sconces.length; i += 2) {
    const x = art.sconces[i];
    if (x > edge) continue;
    const y = art.sconces[i + 1];
    // Two incommensurable rates per torch, so no two ever pulse together.
    const k = Math.sin(t * 7 + i) * 0.5 + Math.sin(t * 11 + i * 2.3) * 0.5;
    const tall = k > 0.2 ? 4 : 2;
    g.fillStyle = k > 0.55 ? SPARK : FRONT_CORE;
    g.fillRect(x - 1, y - tall, 2, tall * 2);
  }
}

/**
 * THE ROUTE — a gold thread drawn down the corridors as far as the bar has got.
 *
 * This is the one element that says the same thing as the percentage without
 * being a number: a way through the maze, being found. It is drawn by DISTANCE
 * rather than by corner count, so it advances at a steady speed instead of
 * crawling through the twisty stretches and sprinting down the straights.
 *
 * Two strokes over ONE path: the path is built once and stroked twice, wide in
 * ember and narrow in flame. Rebuilding it for the second pass would double the
 * only per-frame geometry on the screen.
 */
function paintThread(g: CanvasRenderingContext2D, art: MazeArt, frac: number): void {
  const pts = art.path;
  const count = pts.length / 2;
  if (count < 2) return;
  const total = art.run[count - 1];
  const target = Math.max(0, Math.min(1, frac)) * total;

  let k = 1;
  while (k < count - 1 && art.run[k] < target) k++;
  const span = art.run[k] - art.run[k - 1];
  const alongK = span > 0 ? Math.max(0, Math.min(1, (target - art.run[k - 1]) / span)) : 1;
  const headX = Math.round(pts[k * 2 - 2] + (pts[k * 2] - pts[k * 2 - 2]) * alongK);
  const headY = Math.round(pts[k * 2 - 1] + (pts[k * 2 + 1] - pts[k * 2 - 1]) * alongK);

  g.lineCap = "butt";
  g.lineJoin = "miter";
  g.beginPath();
  g.moveTo(pts[0], pts[1]);
  for (let i = 1; i < k; i++) g.lineTo(pts[i * 2], pts[i * 2 + 1]);
  g.lineTo(headX, headY);

  g.strokeStyle = THREAD_GLOW;
  g.lineWidth = 8;
  g.stroke();
  g.strokeStyle = THREAD_CORE;
  g.lineWidth = 4;
  g.stroke();

  g.fillStyle = SPARK;
  g.fillRect(headX - 4, headY - 4, 8, 8);
}

/** Embers drifting up through the lit stretch. Fourteen `fillRect`s, no state. */
function paintMotes(g: CanvasRenderingContext2D, art: MazeArt, edge: number, t: number): void {
  g.fillStyle = MOTE;
  for (let i = 0; i < 14; i++) {
    const x = ((i * 2654435761) % 1000) / 1000 * art.w;
    if (x > edge) continue;
    const speed = 14 + (i % 5) * 9;
    const y = art.h - (((i * 37) % art.h) + t * speed) % art.h;
    g.fillRect(Math.round(x), Math.round(y), 2, 2);
  }
}

/** The gold rule with a diamond at its centre, under the depth numeral. */
function divider(f: UiFrame, cx: number, y: number, half: number): void {
  fillRect(f, rect(cx - half, y, half - 8, 1), UI.sheetEdge);
  fillRect(f, rect(cx + 8, y, half - 8, 1), UI.sheetEdge);
  fillRect(f, rect(cx - 2, y - 2, 5, 5), UI.gold);
}

export function openFloorLoading(level: number): FloorLoading {
  live = {
    level,
    progress: 0,
    label: "WAKING THE STONE",
    startedAt: performance.now(),
    artW: 0,
    artH: 0,
    art: null,
  };
  const screen: UiScreen = {
    id: "floor-loading",
    // Pauses, but nothing is running underneath anyway — the sim is between
    // floors. The flag matters so a stray key cannot act on the old floor.
    pauses: true,
    focus: 0,
    scroll: 0,
    design: DESIGN,
    // Not dismissable: closing it would reveal a half-built floor.
    onCancel: () => true,
    onClose: () => {
      live = null;
    },
    paint(f) {
      const s = live;
      if (!s) return;
      ensureArt(s, f);

      // MAX of reported progress and a slow wall-clock creep. If the build
      // blocks the loop, the reported value stops arriving; the creep keeps the
      // bar honest-looking without ever overtaking real progress by much.
      const elapsed = performance.now() - s.startedAt;
      const creep = Math.min(0.9, elapsed / 4000);
      const frac = Math.max(s.progress, creep);

      // Opaque, not a scrim: what is behind this is a half-built floor and it
      // must not show through. The backdrop covers the field anyway — this is
      // the guarantee for the slack pixels at the right and bottom edge.
      fillRect(f, rect(0, 0, f.w, f.h), C(0));
      if (s.art) paintBackdrop(f, s.art, frac, elapsed / 1000);

      const cx = Math.round(f.w / 2);
      const top = Math.round(f.h / 2) - 56;

      // ── THE PLATE ──
      // The title used to float on the darkened labyrinth, which put 24px type
      // straight onto a busy, moving, half-lit field: the letterforms competed
      // with the sweep for every pixel of their own edges. A stone slab behind
      // it is the id-software answer and the correct one — it gives the type a
      // quiet surface, and it makes the caption block read as ONE object rather
      // than as four independent things that happen to be centred.
      // Tall enough to hold the bar and the percentage as well as the type: a
      // plate that stopped above the bar left the instrument stranded on the
      // labyrinth, reading as two unrelated widgets that happened to line up.
      const plate = rect(cx - 152, top - 16, 304, 148);
      // A hard offset shadow, the way every menu in this family casts one. It
      // is what lifts the plate off a field that is now BRIGHTER than the plate
      // in the lit half of the screen — the old flat 50% scrim used to do this
      // job by flattening everything, at the cost of the labyrinth.
      fillRect(f, rect(plate.x + 5, plate.y + 5, plate.w, plate.h), C(0));
      fillRect(f, plate, UI.sheet);
      bevel(f, plate, { weight: 2 });
      strokeRect(f, plate, UI.sheetEdge, 1);
      f.g.fillStyle = UI.rivet;
      for (const [sx, sy] of [
        [plate.x + 5, plate.y + 5],
        [plate.x + plate.w - 7, plate.y + 5],
        [plate.x + 5, plate.y + plate.h - 7],
        [plate.x + plate.w - 7, plate.y + plate.h - 7],
      ]) {
        f.g.fillRect(sx, sy, 2, 2);
      }

      // GHOST MAZE CAPTIONS ITSELF. A screenshot taken on the dev workbench
      // must be impossible to mistake for one from a real run — that is the
      // difference between a workbench and a flag that quietly changes what you
      // are looking at, and it is the same reason the floor lock logs on every
      // clamp. Rendered here rather than in `core.ts` because the loading
      // screen already owns "what is this floor called".
      const pinned = ghostFloorLabel();
      text(f, pinned ? "DEV PIN" : "DESCENDING", cx, top, { size: 8, colour: UI.gold, align: "center" });
      // The numeral is cut into the slab: one pass in the void colour, offset
      // down-right, then the face on top. Two `fillText`s, and it is the whole
      // difference between type sitting ON a panel and type cut INTO one — the
      // same chisel the bevel gives every other surface in this UI.
      const depth = pinned ? "GHOST MAZE" : `DEPTH ${s.level}`;
      text(f, depth, cx + 2, top + 22, { size: 24, colour: C(0), align: "center" });
      text(f, depth, cx, top + 20, { size: 24, colour: UI.text, align: "center" });
      divider(f, cx, top + 58, 96);
      text(f, (pinned ?? s.label).toUpperCase(), cx, top + 70, { size: 8, colour: UI.arcane, align: "center" });

      // The bar reads as an INSTRUMENT: a sunken well filled in blocks, the way
      // a Doom status bar fills. See `bar()` — the segmentation is not only the
      // house style, it is the only rendering that cannot shimmer as the value
      // creeps across a fractional pixel boundary, and this is the one bar in
      // the game a player watches for several uninterrupted seconds.
      const track = rect(cx - 128, top + 92, 256, 14);
      bar(f, track, frac);
      strokeRect(f, track, UI.sheetEdge, 1);

      text(f, `${Math.round(frac * 100)}%`, cx, track.y + track.h + GRID, {
        size: 8,
        colour: UI.textDim,
        align: "center",
      });
    },
  };
  push(screen);

  return {
    phase(label, frac) {
      if (!live) return;
      live.label = label;
      // Monotonic, like the DOM version: never let the bar retreat.
      live.progress = Math.max(live.progress, Math.max(0, Math.min(1, frac)));
    },
    close() {
      close("floor-loading");
    },
  };
}
