/**
 * THE DESCENT SCREEN — the loading state between pressing down and playing.
 *
 * WHY THIS EXISTS. Entering a floor used to freeze the tab for five seconds on
 * a black screen. Measured on real hardware (NVIDIA, WebGPU): `startLevel`
 * itself costs ~550ms, and the FIRST FRAME after it cost 5103ms — because
 * WebGPU compiles one render pipeline per distinct material, lazily, the first
 * time each is drawn. So the wait was never "generating the maze"; it was the
 * GPU compiling a floor's worth of shaders while the main thread sat blocked.
 *
 * A progress bar over the generator alone would therefore have covered ~10% of
 * the wait and then handed the player a five-second frozen frame anyway. What
 * makes this screen honest is the pipeline warm-up that runs BEHIND it
 * (`warmFloorPipelines` in core.ts): the compile is moved here, in batches, on
 * purpose, and the bar tracks the batches. That is the same trick Unity's
 * shader prewarm and Unreal's PSO precaching use, and it is why this file
 * exists rather than a bare spinner.
 *
 * ── WHY THE MAZE ON SCREEN IS NOT THE REAL ONE ────────────────────────────
 *
 * It would be easy to draw `state.grid` here — the floor is fully generated by
 * the time the bar is moving, and `map-render.ts` already knows how. It would
 * also hand the player the finished map of a floor they are about to explore,
 * which is the exact spoiler the fog exists to prevent (`startLevel` resets fog
 * every descent for this reason). So this grows its OWN throwaway labyrinth in
 * the same visual language — the track-first circuit look, gold arteries on
 * cold stone — and the player learns nothing from studying it.
 */
import { ensurePixelFonts } from "./pixel-fonts";

const LABEL = "'Press Start 2P', ui-monospace, monospace";

/** Palette, matching the HUD/toast gold + the machine's arcane cyan. */
const GOLD = "#f0a63c";
const ARCANE = "#6fd0e8";
const STONE = "#1a1f2b";
const VOID = "#05070b";

/** Cell states in the throwaway labyrinth drawn behind the bar. */
const WALL = 0;
const FLOOR_ = 1;
const ARTERY = 2;

export interface FloorLoading {
  /** Update the caption + bar. `frac` is clamped to [0,1] and never goes back. */
  phase(label: string, frac: number): void;
  /** Fade out and remove. Safe to call twice. */
  close(): void;
}

interface Cell {
  x: number;
  y: number;
}

/**
 * Grow a decorative labyrinth with a wide gold "artery" threaded through it —
 * the same shape language as a real floor (a circuit the maze fills in around)
 * without being any actual floor. Deliberately unseeded: this is decoration,
 * and a different pattern every descent reads as a different place.
 */
function growLabyrinth(w: number, h: number): Uint8Array {
  const g = new Uint8Array(w * h); // all WALL
  const at = (x: number, y: number): number => y * w + x;
  const inside = (x: number, y: number): boolean => x > 0 && y > 0 && x < w - 1 && y < h - 1;

  // ── Growing-tree maze on odd cells (the surround) ──
  const stack: Cell[] = [];
  const start = { x: 1, y: 1 };
  g[at(start.x, start.y)] = FLOOR_;
  stack.push(start);
  const DIRS = [
    [2, 0],
    [-2, 0],
    [0, 2],
    [0, -2],
  ] as const;
  while (stack.length) {
    // Mostly depth-first (long corridors), sometimes random (junctions).
    const i = Math.random() < 0.7 ? stack.length - 1 : (Math.random() * stack.length) | 0;
    const c = stack[i];
    const opts = DIRS.filter(([dx, dy]) => inside(c.x + dx, c.y + dy) && g[at(c.x + dx, c.y + dy)] === WALL);
    if (!opts.length) {
      stack.splice(i, 1);
      continue;
    }
    const [dx, dy] = opts[(Math.random() * opts.length) | 0];
    g[at(c.x + dx / 2, c.y + dy / 2)] = FLOOR_;
    g[at(c.x + dx, c.y + dy)] = FLOOR_;
    stack.push({ x: c.x + dx, y: c.y + dy });
  }

  // ── The artery: a fat wandering loop carved over the top, so the eye has a
  //    through-line to follow while the bar fills. Two horizontal runs joined
  //    at the ends, wobbled vertically — reads as a circuit, not a corridor. ──
  const carve = (x: number, y: number): void => {
    for (let oy = -1; oy <= 1; oy++) {
      for (let ox = -1; ox <= 1; ox++) {
        if (inside(x + ox, y + oy)) g[at(x + ox, y + oy)] = ARTERY;
      }
    }
  };
  const yTop = Math.floor(h * 0.3);
  const yBot = Math.floor(h * 0.72);
  let y = yTop;
  for (let x = 2; x < w - 2; x++) {
    if (Math.random() < 0.18) y += Math.random() < 0.5 ? 1 : -1;
    y = Math.max(2, Math.min(h - 3, y));
    carve(x, y);
  }
  for (let yy = yTop; yy <= yBot; yy++) carve(w - 3, yy);
  y = yBot;
  for (let x = w - 3; x > 2; x--) {
    if (Math.random() < 0.18) y += Math.random() < 0.5 ? 1 : -1;
    y = Math.max(2, Math.min(h - 3, y));
    carve(x, y);
  }
  for (let yy = yTop; yy <= yBot; yy++) carve(2, yy);
  return g;
}

let host: HTMLDivElement | null = null;

export function isFloorLoadingOpen(): boolean {
  return host !== null;
}

/**
 * Raise the descent screen. Returns the handle the caller drives; the caller is
 * responsible for closing it, including on a failure path.
 */
export function openFloorLoading(container: HTMLElement, level: number): FloorLoading {
  ensurePixelFonts();
  // Never stack two. A second descent while one is up replaces it.
  if (host) host.remove();

  const el = document.createElement("div");
  el.id = "dungeon-floor-loading";
  el.style.cssText = [
    "position:fixed",
    "inset:0",
    // Above the HUD and the map, below the pause menu (10008).
    "z-index:10007",
    `background:${VOID}`,
    // It covers the whole screen while the GPU is busy: swallow input rather
    // than let a click land on the world being built underneath.
    "pointer-events:auto",
    "opacity:0",
    "transition:opacity 0.18s ease",
    "display:flex",
    "align-items:center",
    "justify-content:center",
    "user-select:none",
  ].join(";");

  const canvas = document.createElement("canvas");
  canvas.style.cssText = "position:absolute;inset:0;width:100%;height:100%;image-rendering:pixelated";
  el.appendChild(canvas);
  const ctx = canvas.getContext("2d");

  // ── Foreground furniture: depth, caption, bar ──
  const panel = document.createElement("div");
  panel.style.cssText = [
    "position:relative",
    "display:flex",
    "flex-direction:column",
    "align-items:center",
    "gap:18px",
    "width:min(520px,80vw)",
    "text-align:center",
  ].join(";");
  panel.innerHTML = `
    <div style="font:22px ${LABEL};color:${GOLD};letter-spacing:6px;text-shadow:0 0 18px rgba(240,166,60,0.45),2px 2px 0 #0b0d12">
      DESCENDING
    </div>
    <div style="font:34px ${LABEL};color:#fff;letter-spacing:4px;text-shadow:0 0 22px rgba(111,208,232,0.5),3px 3px 0 #0b0d12">
      DEPTH ${level}
    </div>
    <div style="display:flex;align-items:center;gap:10px;width:100%">
      <span style="flex:1;height:1px;background:linear-gradient(90deg,transparent,${GOLD})"></span>
      <span style="width:7px;height:7px;background:${GOLD};transform:rotate(45deg)"></span>
      <span style="flex:1;height:1px;background:linear-gradient(90deg,${GOLD},transparent)"></span>
    </div>
    <div id="dfl-cap" style="font:10px ${LABEL};color:${ARCANE};letter-spacing:3px;min-height:14px">
      WAKING THE STONE
    </div>
    <div style="position:relative;width:100%;height:16px;background:#0b0d12;border:2px solid #3a3f4b;box-shadow:inset 0 0 12px rgba(0,0,0,0.8)">
      <div id="dfl-bar" style="position:absolute;left:0;top:0;bottom:0;width:0%;
        background:linear-gradient(90deg,${GOLD},#ffd9a0);
        box-shadow:0 0 14px rgba(240,166,60,0.7);transition:width 0.25s ease"></div>
    </div>
    <div id="dfl-pct" style="font:9px ${LABEL};color:#6b7488;letter-spacing:2px">0%</div>
  `;
  el.appendChild(panel);
  container.appendChild(el);
  host = el;
  requestAnimationFrame(() => {
    el.style.opacity = "1";
  });

  const cap = panel.querySelector("#dfl-cap") as HTMLDivElement;
  const bar = panel.querySelector("#dfl-bar") as HTMLDivElement;
  const pct = panel.querySelector("#dfl-pct") as HTMLDivElement;

  // ── The animated labyrinth behind the panel ──
  const CELL = 14;
  let cols = 0;
  let rows = 0;
  let maze: Uint8Array = new Uint8Array(0);
  const size = (): void => {
    const w = window.innerWidth;
    const h = window.innerHeight;
    canvas.width = w;
    canvas.height = h;
    const nc = Math.ceil(w / CELL) + 1;
    const nr = Math.ceil(h / CELL) + 1;
    if (nc !== cols || nr !== rows) {
      cols = nc;
      rows = nr;
      maze = growLabyrinth(cols, rows);
    }
    if (ctx) ctx.imageSmoothingEnabled = false;
  };
  size();
  window.addEventListener("resize", size);

  let frac = 0;
  let raf = 0;
  const t0 = performance.now();
  const paint = (): void => {
    raf = requestAnimationFrame(paint);
    if (!ctx) return;
    const t = (performance.now() - t0) / 1000;
    const w = canvas.width;
    const h = canvas.height;
    ctx.fillStyle = VOID;
    ctx.fillRect(0, 0, w, h);

    // The whole labyrinth is laid out from the first frame, in cold unlit
    // stone, and the progress sweep ENERGISES it left to right. Revealing the
    // tiles themselves instead left half the screen empty black for half the
    // descent, which reads as "nothing is happening" — the opposite of what a
    // loading screen is for.
    const edge = frac * (cols + 8);
    for (let j = 0; j < rows; j++) {
      for (let i = 0; i < cols; i++) {
        const kind = maze[j * cols + i];
        if (kind === WALL) continue;
        const d = edge - i; // >0 once the sweep has passed this column
        const lit = Math.max(0, Math.min(1, d / 6));
        const x = i * CELL;
        const y = j * CELL;
        if (kind === ARTERY) {
          // The gold through-line, with a travelling pulse once it is live.
          const pulse = 0.55 + 0.45 * Math.sin(t * 3 - i * 0.35);
          const a = 0.1 + (0.12 + 0.5 * pulse) * lit;
          ctx.fillStyle = `rgba(240,166,60,${a})`;
        } else {
          ctx.fillStyle = `rgba(26,31,43,${0.34 + 0.61 * lit})`;
        }
        ctx.fillRect(x, y, CELL - 1, CELL - 1);
        // A cold rim rides the leading edge — tiles snapping into place.
        if (d > 0 && d < 6 && kind !== ARTERY) {
          ctx.fillStyle = `rgba(111,208,232,${0.5 * (1 - d / 6)})`;
          ctx.fillRect(x, y, CELL - 1, 2);
        }
      }
    }

    // Vignette + scanlines — the same CRT read as the rest of the game.
    const g = ctx.createRadialGradient(w / 2, h / 2, Math.min(w, h) * 0.25, w / 2, h / 2, Math.max(w, h) * 0.75);
    g.addColorStop(0, "rgba(0,0,0,0)");
    g.addColorStop(1, "rgba(0,0,0,0.85)");
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, w, h);
    ctx.fillStyle = "rgba(0,0,0,0.16)";
    for (let y = 0; y < h; y += 3) ctx.fillRect(0, y, w, 1);
  };
  raf = requestAnimationFrame(paint);

  let closed = false;
  return {
    phase(label: string, f: number): void {
      if (closed) return;
      // Monotonic: a bar that goes backwards reads as a bug, not as progress.
      frac = Math.max(frac, Math.min(1, Math.max(0, f)));
      cap.textContent = label;
      bar.style.width = `${(frac * 100).toFixed(0)}%`;
      pct.textContent = `${Math.round(frac * 100)}%`;
    },
    close(): void {
      if (closed) return;
      closed = true;
      window.removeEventListener("resize", size);
      cancelAnimationFrame(raf);
      el.style.opacity = "0";
      window.setTimeout(() => {
        el.remove();
        if (host === el) host = null;
      }, 200);
    },
  };
}
