//! Enemy types, stats table, and live monster runtime data.
//!
//! PORTS: `constants/enemies.ts`, `entities/enemy-rules.ts`, `bestiary.ts`
//! PORTS-PARTIAL: `spawn/factory.ts` - NOT a finished port - 0 of 14 exported names carried over (0%). Downgraded by the 2026-08-16 ledger audit; see docs/src/status/incidents.md

use crate::enemies::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EnemyKind {
    Zombie,
    Brute,
    Croaker,
    Goblin,
    Jester,
    Reaper,
    Slime,
    Spider,
    Stiltneck,
    Bat,
    Chomper,
    Ghost,
    Golem,
    Skeleton,
    Witch,
    Mimic,
    Rotortail,
    BossKing,
    Spitter,
    Pin,
    Webspinner,
    Sporeling,
    FishFeet,
    Hound,
    Bloater,
    Necromancer,
    Warden,
    Wisp,
    Sapper,
    Crystalback,
    Magnet,
}

impl EnemyKind {
    pub const ALL: [Self; 31] = [
        Self::Zombie,
        Self::Brute,
        Self::Croaker,
        Self::Goblin,
        Self::Jester,
        Self::Reaper,
        Self::Slime,
        Self::Spider,
        Self::Stiltneck,
        Self::Bat,
        Self::Chomper,
        Self::Ghost,
        Self::Golem,
        Self::Skeleton,
        Self::Witch,
        Self::Mimic,
        Self::Rotortail,
        Self::BossKing,
        Self::Spitter,
        Self::Pin,
        Self::Webspinner,
        Self::Sporeling,
        Self::FishFeet,
        Self::Hound,
        Self::Bloater,
        Self::Necromancer,
        Self::Warden,
        Self::Wisp,
        Self::Sapper,
        Self::Crystalback,
        Self::Magnet,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Zombie => "zombie",
            Self::Brute => "brute",
            Self::Croaker => "croaker",
            Self::Goblin => "goblin",
            Self::Jester => "jester",
            Self::Reaper => "reaper",
            Self::Slime => "slime",
            Self::Spider => "spider",
            Self::Stiltneck => "stiltneck",
            Self::Bat => "bat",
            Self::Chomper => "chomper",
            Self::Ghost => "ghost",
            Self::Golem => "golem",
            Self::Skeleton => "skeleton",
            Self::Witch => "witch",
            Self::Mimic => "mimic",
            Self::Rotortail => "rotortail",
            Self::BossKing => "boss_king",
            Self::Spitter => "spitter",
            Self::Pin => "pin",
            Self::Webspinner => "webspinner",
            Self::Sporeling => "sporeling",
            Self::FishFeet => "fish_feet",
            Self::Hound => "hound",
            Self::Bloater => "bloater",
            Self::Necromancer => "necromancer",
            Self::Warden => "warden",
            Self::Wisp => "wisp",
            Self::Sapper => "sapper",
            Self::Crystalback => "crystalback",
            Self::Magnet => "magnet",
        }
    }

    pub fn from_str_id(s: &str) -> Option<Self> {
        match s {
            "zombie" => Some(Self::Zombie),
            "brute" => Some(Self::Brute),
            "croaker" | "frog" => Some(Self::Croaker),
            "goblin" => Some(Self::Goblin),
            "jester" => Some(Self::Jester),
            "reaper" => Some(Self::Reaper),
            "slime" => Some(Self::Slime),
            "spider" => Some(Self::Spider),
            "stiltneck" => Some(Self::Stiltneck),
            "bat" => Some(Self::Bat),
            "chomper" => Some(Self::Chomper),
            "ghost" => Some(Self::Ghost),
            "golem" => Some(Self::Golem),
            "skeleton" => Some(Self::Skeleton),
            "witch" => Some(Self::Witch),
            "mimic" => Some(Self::Mimic),
            "rotortail" => Some(Self::Rotortail),
            "boss_king" | "boss" => Some(Self::BossKing),
            "spitter" => Some(Self::Spitter),
            "pin" => Some(Self::Pin),
            "webspinner" => Some(Self::Webspinner),
            "sporeling" => Some(Self::Sporeling),
            "fish_feet" => Some(Self::FishFeet),
            "hound" => Some(Self::Hound),
            "bloater" => Some(Self::Bloater),
            "necromancer" => Some(Self::Necromancer),
            "warden" => Some(Self::Warden),
            "wisp" => Some(Self::Wisp),
            "sapper" => Some(Self::Sapper),
            "crystalback" => Some(Self::Crystalback),
            "magnet" => Some(Self::Magnet),
            _ => None,
        }
    }

    pub const fn def(self) -> MonsterDef {
        match self {
            Self::Zombie => MonsterDef {
                kind: Self::Zombie,
                label: "Zombie",
                hp: ZOMBIE_HP,
                speed_factor: 1.0,
                radius: ZOMBIE_R,
                contact_range: 0.65,
                windup: ZOMBIE_ATTACK_WINDUP,
                cooldown: ZOMBIE_ATTACK_COOLDOWN,
                damage: ZOMBIE_DAMAGE,
                from_level: 1,
            },
            Self::Brute => MonsterDef {
                kind: Self::Brute,
                label: "Brute",
                hp: BRUTE_HP,
                speed_factor: BRUTE_SPEED_FACTOR,
                radius: BRUTE_R,
                contact_range: BRUTE_CONTACT_RANGE,
                windup: BRUTE_ATTACK_WINDUP,
                cooldown: BRUTE_ATTACK_COOLDOWN,
                damage: BRUTE_DAMAGE,
                from_level: 3,
            },
            Self::Croaker => MonsterDef {
                kind: Self::Croaker,
                label: "Croaker",
                hp: CROAKER_HP,
                speed_factor: CROAKER_SPEED_FACTOR,
                radius: CROAKER_R,
                contact_range: 0.6,
                windup: CROAKER_WINDUP,
                cooldown: CROAKER_COOLDOWN,
                damage: CROAKER_BEAM_DAMAGE,
                from_level: 2,
            },
            Self::Goblin => MonsterDef {
                kind: Self::Goblin,
                label: "Goblin",
                hp: GOBLIN_HP,
                speed_factor: GOBLIN_SPEED_FACTOR,
                radius: GOBLIN_R,
                contact_range: 0.55,
                windup: 0.2,
                cooldown: GOBLIN_KICK_COOLDOWN,
                damage: 1,
                from_level: 1,
            },
            Self::Jester => MonsterDef {
                kind: Self::Jester,
                label: "Jester",
                hp: 4,
                speed_factor: 1.1,
                radius: 0.32,
                contact_range: 0.7,
                windup: 0.3,
                cooldown: JESTER_COOLDOWN,
                damage: JESTER_DISC_DAMAGE,
                from_level: 3,
            },
            Self::Reaper => MonsterDef {
                kind: Self::Reaper,
                label: "Reaper",
                hp: 999, // Invulnerable death dealer
                speed_factor: 0.55,
                radius: 0.45,
                contact_range: 1.1,
                windup: 0.45,
                cooldown: 1.2,
                damage: 99,
                from_level: 4,
            },
            Self::Slime => MonsterDef {
                kind: Self::Slime,
                label: "Slime",
                hp: 3,
                speed_factor: 0.65,
                radius: 0.38,
                contact_range: 0.6,
                windup: 0.35,
                cooldown: 0.7,
                damage: 1,
                from_level: 1,
            },
            Self::Spider => MonsterDef {
                kind: Self::Spider,
                label: "Spider",
                hp: SPIDER_HP,
                speed_factor: SPIDER_SPEED_FACTOR,
                radius: SPIDER_R,
                contact_range: 0.6,
                windup: 0.22,
                cooldown: 0.65,
                damage: 1,
                from_level: 1,
            },
            Self::Stiltneck => MonsterDef {
                kind: Self::Stiltneck,
                label: "Stiltneck",
                hp: STILTNECK_HP,
                speed_factor: STILTNECK_SPEED_FACTOR,
                radius: STILTNECK_R,
                contact_range: 0.8,
                windup: 0.4,
                cooldown: STILTNECK_COOLDOWN,
                damage: 2,
                from_level: 3,
            },
            Self::Bat => MonsterDef {
                kind: Self::Bat,
                label: "Bat",
                hp: BAT_HP,
                speed_factor: BAT_SPEED_FACTOR,
                radius: BAT_R,
                contact_range: BAT_CONTACT_RANGE,
                windup: BAT_ATTACK_WINDUP,
                cooldown: BAT_ATTACK_COOLDOWN,
                damage: BAT_DAMAGE,
                from_level: 3,
            },
            Self::Chomper => MonsterDef {
                kind: Self::Chomper,
                label: "Chomper",
                hp: CHOMPER_HP,
                speed_factor: 0.8,
                radius: CHOMPER_R,
                contact_range: CHOMPER_CONTACT_RANGE,
                windup: CHOMPER_ATTACK_WINDUP,
                cooldown: CHOMPER_ATTACK_COOLDOWN,
                damage: CHOMPER_DAMAGE,
                from_level: 2,
            },
            Self::Ghost => MonsterDef {
                kind: Self::Ghost,
                label: "Ghost",
                hp: GHOST_HP,
                speed_factor: GHOST_SPEED_FACTOR,
                radius: GHOST_R,
                contact_range: GHOST_CONTACT_RANGE,
                windup: GHOST_ATTACK_WINDUP,
                cooldown: GHOST_ATTACK_COOLDOWN,
                damage: GHOST_DAMAGE,
                from_level: 2,
            },
            Self::Golem => MonsterDef {
                kind: Self::Golem,
                label: "Golem",
                hp: GOLEM_HP,
                speed_factor: 0.5,
                radius: GOLEM_R,
                contact_range: GOLEM_CONTACT_RANGE,
                windup: GOLEM_ATTACK_WINDUP,
                cooldown: GOLEM_ATTACK_COOLDOWN,
                damage: GOLEM_DAMAGE,
                from_level: 3,
            },
            Self::Skeleton => MonsterDef {
                kind: Self::Skeleton,
                label: "Skeleton",
                hp: 4,
                speed_factor: 1.0,
                radius: 0.32,
                contact_range: 0.65,
                windup: 0.3,
                cooldown: 1.0,
                damage: 1,
                from_level: 2,
            },
            Self::Witch => MonsterDef {
                kind: Self::Witch,
                label: "Witch",
                hp: 3,
                speed_factor: 0.85,
                radius: 0.34,
                contact_range: 6.0,
                windup: 0.5,
                cooldown: 2.2,
                damage: 1,
                from_level: 3,
            },
            Self::Mimic => MonsterDef {
                kind: Self::Mimic,
                label: "Mimic",
                hp: 6,
                speed_factor: 1.25,
                radius: 0.36,
                contact_range: 0.7,
                windup: 0.2,
                cooldown: 0.8,
                damage: 2,
                from_level: 3,
            },
            Self::Rotortail => MonsterDef {
                kind: Self::Rotortail,
                label: "Rotortail",
                hp: 5,
                speed_factor: 0.75,
                radius: 0.38,
                contact_range: 5.5,
                windup: 0.4,
                cooldown: 1.8,
                damage: 1,
                from_level: 3,
            },
            Self::BossKing => MonsterDef {
                kind: Self::BossKing,
                label: "King Zombie",
                hp: BOSS_BASE_HP,
                speed_factor: BOSS_SPEED_FACTOR,
                radius: 0.75,
                contact_range: 1.4,
                windup: 0.6,
                cooldown: 1.5,
                damage: 3,
                from_level: 5,
            },
            Self::Spitter => MonsterDef {
                kind: Self::Spitter,
                label: "Spitter",
                hp: ZOMBIE_HP,
                speed_factor: 1.0,
                radius: ZOMBIE_R,
                contact_range: 4.5,
                windup: 0.4,
                cooldown: 1.8,
                damage: ZOMBIE_DAMAGE,
                from_level: 2,
            },
            Self::Pin => MonsterDef {
                kind: Self::Pin,
                label: "Pin",
                hp: ZOMBIE_HP,
                speed_factor: 0.8,
                radius: ZOMBIE_R,
                contact_range: 0.6,
                windup: 0.2,
                cooldown: 1.0,
                damage: ZOMBIE_DAMAGE,
                from_level: 2,
            },
            Self::Webspinner => MonsterDef {
                kind: Self::Webspinner,
                label: "Webspinner",
                hp: SPIDER_HP,
                speed_factor: SPIDER_SPEED_FACTOR,
                radius: SPIDER_R,
                contact_range: 3.5,
                windup: 0.3,
                cooldown: 1.5,
                damage: SPIDER_DAMAGE,
                from_level: 2,
            },
            Self::Sporeling => MonsterDef {
                kind: Self::Sporeling,
                label: "Sporeling",
                hp: ZOMBIE_HP,
                speed_factor: 0.9,
                radius: ZOMBIE_R,
                contact_range: 0.6,
                windup: 0.3,
                cooldown: 1.2,
                damage: ZOMBIE_DAMAGE,
                from_level: 2,
            },
            Self::FishFeet => MonsterDef {
                kind: Self::FishFeet,
                label: "Fish Feet",
                hp: ZOMBIE_HP,
                speed_factor: 1.2,
                radius: ZOMBIE_R,
                contact_range: 0.6,
                windup: 0.2,
                cooldown: 0.8,
                damage: ZOMBIE_DAMAGE,
                from_level: 3,
            },
            Self::Hound => MonsterDef {
                kind: Self::Hound,
                label: "Hound",
                hp: SPIDER_HP,
                speed_factor: 1.4,
                radius: SPIDER_R,
                contact_range: 0.6,
                windup: 0.2,
                cooldown: 0.8,
                damage: SPIDER_DAMAGE,
                from_level: 2,
            },
            Self::Bloater => MonsterDef {
                kind: Self::Bloater,
                label: "Bloater",
                hp: ZOMBIE_HP * 2,
                speed_factor: 0.7,
                radius: ZOMBIE_R * 1.3,
                contact_range: 0.8,
                windup: 0.5,
                cooldown: 2.0,
                damage: ZOMBIE_DAMAGE,
                from_level: 3,
            },
            Self::Necromancer => MonsterDef {
                kind: Self::Necromancer,
                label: "Necromancer",
                hp: ZOMBIE_HP * 2,
                speed_factor: 0.9,
                radius: ZOMBIE_R,
                contact_range: 5.0,
                windup: 0.6,
                cooldown: 3.0,
                damage: ZOMBIE_DAMAGE,
                from_level: 4,
            },
            Self::Warden => MonsterDef {
                kind: Self::Warden,
                label: "Warden",
                hp: BRUTE_HP,
                speed_factor: BRUTE_SPEED_FACTOR,
                radius: BRUTE_R,
                contact_range: BRUTE_CONTACT_RANGE,
                windup: BRUTE_ATTACK_WINDUP,
                cooldown: BRUTE_ATTACK_COOLDOWN,
                damage: BRUTE_DAMAGE,
                from_level: 4,
            },
            Self::Wisp => MonsterDef {
                kind: Self::Wisp,
                label: "Wisp",
                hp: GHOST_HP,
                speed_factor: 1.3,
                radius: 0.35,
                contact_range: 0.6,
                windup: 0.2,
                cooldown: 1.0,
                damage: GHOST_DAMAGE,
                from_level: 3,
            },
            Self::Sapper => MonsterDef {
                kind: Self::Sapper,
                label: "Sapper",
                hp: SPIDER_HP,
                speed_factor: 1.2,
                radius: SPIDER_R,
                contact_range: 0.6,
                windup: 0.2,
                cooldown: 0.8,
                damage: SPIDER_DAMAGE,
                from_level: 3,
            },
            Self::Crystalback => MonsterDef {
                kind: Self::Crystalback,
                label: "Crystalback",
                hp: GOLEM_HP,
                speed_factor: 0.5,
                radius: GOLEM_R,
                contact_range: 0.7,
                windup: 0.4,
                cooldown: 1.5,
                damage: GOLEM_DAMAGE,
                from_level: 4,
            },
            Self::Magnet => MonsterDef {
                kind: Self::Magnet,
                label: "Magnet",
                hp: GOLEM_HP,
                speed_factor: 0.8,
                radius: GOLEM_R,
                contact_range: 0.7,
                windup: 0.3,
                cooldown: 1.5,
                damage: MAGNET_DAMAGE,
                from_level: 4,
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MonsterDef {
    pub kind: EnemyKind,
    pub label: &'static str,
    pub hp: i32,
    pub speed_factor: f64,
    pub radius: f64,
    pub contact_range: f64,
    pub windup: f64,
    pub cooldown: f64,
    pub damage: i32,
    pub from_level: u32,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EnemyMode {
    Wander,
    Chase,
    Windup,
    Attack,
    Hop,
    Stagger,
    Dead,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LiveMonster {
    pub id: u32,
    pub kind: EnemyKind,
    pub x: f64,
    pub z: f64,
    pub vx: f64,
    pub vz: f64,
    pub radius: f64,
    pub hp: f64,
    pub max_hp: f64,
    pub speed: f64,
    pub mode: EnemyMode,
    pub windup_t: f64,
    pub attack_cd: f64,
    pub stagger_t: f64,
    pub contact_range: f64,
    pub windup_duration: f64,
    pub cooldown_duration: f64,
    pub damage: i32,
    // --- Special ability states ---
    pub hop_t: f64,
    pub hop_cd: f64,
    pub hop_bounces: i32,
    pub bob_t: f64,
    pub vuln_t: f64,
    pub kbx: f64,
    pub kbz: f64,
    pub knock_t: f64,
}

impl LiveMonster {
    pub fn new(id: u32, kind: EnemyKind, x: f64, z: f64) -> Self {
        let def = kind.def();
        Self {
            id,
            kind,
            x,
            z,
            vx: 0.0,
            vz: 0.0,
            radius: def.radius,
            hp: f64::from(def.hp),
            max_hp: f64::from(def.hp),
            speed: 1.6 * def.speed_factor,
            mode: EnemyMode::Chase,
            windup_t: 0.0,
            attack_cd: 0.0,
            stagger_t: 0.0,
            contact_range: def.contact_range,
            windup_duration: def.windup,
            cooldown_duration: def.cooldown,
            damage: def.damage,
            hop_t: 0.0,
            hop_cd: 0.0,
            hop_bounces: 0,
            bob_t: 0.0,
            vuln_t: 0.0,
            kbx: 0.0,
            kbz: 0.0,
            knock_t: 0.0,
        }
    }

    pub fn is_alive(&self) -> bool {
        self.mode != EnemyMode::Dead && self.hp > 0.0
    }
}
