/**
 * Canonical Projectile VFX Configuration Registry.
 *
 * Maps every ProjectileKind in the game to its visual archetype, dimension tuning,
 * color palette, in-flight dynamics, launch tells, and impact parameters.
 */
import type { ProjectileKind } from "../../items";
import type { ProjectileVfxConfig } from "./types";

export const PROJECTILE_VFX_CONFIGS: Record<string, ProjectileVfxConfig> = {
  // ── 1. Guns & Bullets (Firearms Tier) ─────────────────────────────────────
  bullet: {
    kind: "bullet",
    archetype: "bullet",
    dimensions: { radius: 0.05, length: 0.18, glowScale: 1.4 },
    colors: { core: 0xffffff, glow: 0xfacc15, accent: 0xa8a29e },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 20, trailType: "sparks", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xfef08a, sparkCount: 5, smokePuff: true },
    impact: { wallType: "sparks", color: 0xfacc15, count: 6 },
  },
  warden_bullet: {
    kind: "bullet",
    archetype: "bullet",
    dimensions: { radius: 0.055, length: 0.20, glowScale: 1.5 },
    colors: { core: 0xffffff, glow: 0xffdd44, accent: 0xd97706 },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 25, trailType: "sparks", trailInterval: 0.03, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xffdd44, sparkCount: 6, smokePuff: true },
    impact: { wallType: "sparks", color: 0xffdd44, count: 8 },
  },
  fish_bullet: {
    kind: "fish_bullet",
    archetype: "bullet",
    dimensions: { radius: 0.045, length: 0.16, glowScale: 1.4 },
    colors: { core: 0xfef08a, glow: 0xd97706, accent: 0xb45309 },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 22, trailType: "sparks", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xfef08a, sparkCount: 4, smokePuff: true },
    impact: { wallType: "sparks", color: 0xd97706, count: 5 },
  },
  octo_bullet: {
    kind: "octo_bullet",
    archetype: "bullet",
    dimensions: { radius: 0.065, length: 0.22, glowScale: 1.35 },
    colors: { core: 0x475569, glow: 0x1e293b, accent: 0x0f172a },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 18, trailType: "smoke", trailInterval: 0.05, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0x94a3b8, sparkCount: 6, smokePuff: true },
    impact: { wallType: "sparks", color: 0x64748b, count: 6 },
  },
  magnum_bullet: {
    kind: "magnum_bullet",
    archetype: "bullet",
    dimensions: { radius: 0.07, length: 0.26, glowScale: 1.6 },
    colors: { core: 0xffffff, glow: 0xfef08a, accent: 0xeab308 },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 28, trailType: "sparks", trailInterval: 0.025, trailCount: 2 },
    launch: { muzzleFlash: true, flashColor: 0xffffff, sparkCount: 8, smokePuff: true },
    impact: { wallType: "sparks", color: 0xfacc15, count: 10, screenShake: 0.05 },
  },
  auto9_bullet: {
    kind: "auto9_bullet",
    archetype: "bullet",
    dimensions: { radius: 0.05, length: 0.19, glowScale: 1.55 },
    colors: { core: 0xffffff, glow: 0x60a5fa, accent: 0x2563eb },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 30, trailType: "sparks", trailInterval: 0.03, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0x93c5fd, sparkCount: 5, smokePuff: false },
    impact: { wallType: "sparks", color: 0x3b82f6, count: 6 },
  },
  sky_bullet: {
    kind: "sky_bullet",
    archetype: "bullet",
    dimensions: { radius: 0.075, length: 0.24, glowScale: 1.5 },
    colors: { core: 0xffedd5, glow: 0xf59e0b, accent: 0xb45309 },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 15, trailType: "smoke", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xf59e0b, sparkCount: 7, smokePuff: true },
    impact: { wallType: "burst", color: 0xf59e0b, count: 12, screenShake: 0.1 },
  },

  // ── 2. Fire & Flames ──────────────────────────────────────────────────────
  zippo_flame: {
    kind: "zippo_flame",
    archetype: "flame",
    dimensions: { radius: 0.12, length: 0.28, glowScale: 1.6 },
    colors: { core: 0xfffbeb, glow: 0xff6600, accent: 0xd97706 },
    flight: { orientToHeading: true, pulseGlow: true, pulseSpeed: 16, trailType: "embers", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xff6600, sparkCount: 6, smokePuff: true },
    impact: { wallType: "burst", color: 0xff6600, count: 10, floorDecal: "fire" },
  },
  falcon_fire_bomb: {
    kind: "falcon_fire_bomb",
    archetype: "flame",
    dimensions: { radius: 0.15, length: 0.35, glowScale: 1.65 },
    colors: { core: 0xffedd5, glow: 0xe11d48, accent: 0x991b1b },
    flight: { orientToHeading: true, pulseGlow: true, trailType: "embers", trailInterval: 0.03, trailCount: 2 },
    launch: { muzzleFlash: true, flashColor: 0xe11d48, sparkCount: 8, smokePuff: true },
    impact: { wallType: "detonate", color: 0xe11d48, count: 14, floorDecal: "fire", screenShake: 0.12 },
  },
  flame: {
    kind: "flame",
    archetype: "flame",
    dimensions: { radius: 0.11, length: 0.24, glowScale: 1.5 },
    colors: { core: 0xfffbeb, glow: 0xf97316, accent: 0xe11d48 },
    flight: { orientToHeading: true, pulseGlow: true, trailType: "embers", trailInterval: 0.03, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xf97316, sparkCount: 5, smokePuff: true },
    impact: { wallType: "burst", color: 0xf97316, count: 8, floorDecal: "fire" },
  },

  // ── 3. Acid, Venom & Biological Globs ─────────────────────────────────────
  glob: {
    kind: "glob",
    archetype: "glob",
    dimensions: { radius: 0.14, glowScale: 1.35 },
    colors: { core: 0xa3e635, glow: 0x4d7c0f, accent: 0xffffff },
    flight: { orientToHeading: false, pulseGlow: true, pulseSpeed: 10, trailType: "caustic", trailInterval: 0.05, trailCount: 1 },
    launch: { muzzleFlash: false, sparkCount: 3, smokePuff: false },
    impact: { wallType: "splash", color: 0x84cc16, count: 8, floorDecal: "rot" },
  },
  web: {
    kind: "web",
    archetype: "glob",
    dimensions: { radius: 0.13, glowScale: 1.3 },
    colors: { core: 0xf8fafc, glow: 0xcfd8dc, accent: 0xffffff },
    flight: { orientToHeading: false, spinAxis: "roll", spinSpeed: 8, trailType: "dust", trailInterval: 0.06, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "splash", color: 0xe2e8f0, count: 6 },
  },
  vulture_sludge_bomb: {
    kind: "vulture_sludge_bomb",
    archetype: "glob",
    dimensions: { radius: 0.16, glowScale: 1.4 },
    colors: { core: 0x84cc16, glow: 0x3f6212, accent: 0xffffff },
    flight: { orientToHeading: false, pulseGlow: true, trailType: "caustic", trailInterval: 0.04, trailCount: 2 },
    launch: { muzzleFlash: false },
    impact: { wallType: "splash", color: 0x4d7c0f, count: 12, floorDecal: "rot" },
  },
  shake_spray: {
    kind: "shake_spray",
    archetype: "glob",
    dimensions: { radius: 0.12, glowScale: 1.3 },
    colors: { core: 0xa3e635, glow: 0x65a30d, accent: 0xffffff },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 10, trailType: "sparks", trailInterval: 0.05, trailCount: 1 },
    launch: { muzzleFlash: false, sparkCount: 5 },
    impact: { wallType: "splash", color: 0x84cc16, count: 8 },
  },

  // ── 4. Energy & Plasma Beams ──────────────────────────────────────────────
  beam: {
    kind: "beam",
    archetype: "beam",
    dimensions: { radius: 0.08, length: 0.45, glowScale: 1.7 },
    colors: { core: 0xffffff, glow: 0xef4444, accent: 0xb91c1c },
    flight: { orientToHeading: true, pulseGlow: true, pulseSpeed: 20, trailType: "laser", trailInterval: 0.025, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0xef4444, sparkCount: 6, smokePuff: false },
    impact: { wallType: "sparks", color: 0xef4444, count: 8 },
  },
  spear_bolt: {
    kind: "spear_bolt",
    archetype: "beam",
    dimensions: { radius: 0.07, length: 0.48, glowScale: 1.6 },
    colors: { core: 0xffffff, glow: 0x38bdf8, accent: 0x0284c7 },
    flight: { orientToHeading: true, trailType: "laser", trailInterval: 0.03, trailCount: 1 },
    launch: { muzzleFlash: true, flashColor: 0x38bdf8, sparkCount: 5, smokePuff: false },
    impact: { wallType: "sparks", color: 0x38bdf8, count: 7 },
  },
  electric_bullet: {
    kind: "electric_bullet",
    archetype: "beam",
    dimensions: { radius: 0.09, length: 0.22, glowScale: 1.8 },
    colors: { core: 0xffffff, glow: 0x67e8f9, accent: 0x06b6d4 },
    flight: { orientToHeading: true, pulseGlow: true, pulseSpeed: 24, trailType: "laser", trailInterval: 0.025, trailCount: 2 },
    launch: { muzzleFlash: true, flashColor: 0x67e8f9, sparkCount: 6 },
    impact: { wallType: "sparks", color: 0x67e8f9, count: 10, floorDecal: "shock" },
  },

  // ── 5. Thrown Blades, Discs & Spikes ──────────────────────────────────────
  disc: {
    kind: "disc",
    archetype: "blade",
    dimensions: { radius: 0.19, glowScale: 1.15 },
    colors: { core: 0xdc2626, glow: 0xffffff, accent: 0x991b1b },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 26, trailType: "sparks", trailInterval: 0.06, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0xdc2626, count: 6 },
  },
  shuriken: {
    kind: "shuriken",
    archetype: "blade",
    dimensions: { radius: 0.15, glowScale: 1.2 },
    colors: { core: 0xe2e8f0, glow: 0x94a3b8, accent: 0x64748b },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 35, trailType: "sparks", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: false, sparkCount: 6 },
    impact: { wallType: "sparks", color: 0xe2e8f0, count: 8 },
  },
  lion_spine: {
    kind: "lion_spine",
    archetype: "blade",
    dimensions: { radius: 0.05, length: 0.32, glowScale: 1.3 },
    colors: { core: 0xa855f7, glow: 0x7e22ce, accent: 0x581c87 },
    flight: { orientToHeading: true, trailType: "sparks", trailInterval: 0.05, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0xa855f7, count: 6 },
  },
  puffer_slug: {
    kind: "puffer_slug",
    archetype: "blade",
    dimensions: { radius: 0.16, glowScale: 1.3 },
    colors: { core: 0x1e293b, glow: 0x475569, accent: 0x0f172a },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 8 },
    launch: { muzzleFlash: false },
    impact: { wallType: "burst", color: 0x94a3b8, count: 12 },
  },
  puffer_spike: {
    kind: "puffer_spike",
    archetype: "blade",
    dimensions: { radius: 0.04, length: 0.22, glowScale: 1.2 },
    colors: { core: 0xf1f5f9, glow: 0x94a3b8, accent: 0x64748b },
    flight: { orientToHeading: true, trailType: "sparks", trailInterval: 0.06, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0xf1f5f9, count: 4 },
  },
  shard: {
    kind: "shard",
    archetype: "blade",
    dimensions: { radius: 0.12, glowScale: 1.2 },
    colors: { core: 0xa8a29e, glow: 0xd6d3d1, accent: 0x78716c },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 14 },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0xa8a29e, count: 5 },
  },
  ice_shard: {
    kind: "ice_shard",
    archetype: "blade",
    dimensions: { radius: 0.11, glowScale: 1.3 },
    colors: { core: 0x67e8f9, glow: 0xa5f3fc, accent: 0x06b6d4 },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 14, trailType: "sparks", trailInterval: 0.05, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0x67e8f9, count: 6 },
  },

  // ── 6. Heavy Ordnance & Bombs ─────────────────────────────────────────────
  bomb: {
    kind: "bomb",
    archetype: "bomb",
    dimensions: { radius: 0.18, glowScale: 1.2 },
    colors: { core: 0x18181b, glow: 0xfacc15, accent: 0x64748b },
    flight: { orientToHeading: false, pulseGlow: true, trailType: "sparks", trailInterval: 0.03, trailCount: 2 },
    launch: { muzzleFlash: true, flashColor: 0xfacc15, sparkCount: 6, smokePuff: true },
    impact: { wallType: "detonate", color: 0xf59e0b, count: 18, screenShake: 0.15 },
  },
  corvid_bomb: {
    kind: "corvid_bomb",
    archetype: "bomb",
    dimensions: { radius: 0.17, glowScale: 1.2 },
    colors: { core: 0x09090b, glow: 0xf59e0b, accent: 0x3f3f46 },
    flight: { orientToHeading: false, pulseGlow: true, trailType: "sparks", trailInterval: 0.03, trailCount: 2 },
    launch: { muzzleFlash: true, flashColor: 0xf59e0b, sparkCount: 5, smokePuff: true },
    impact: { wallType: "detonate", color: 0xf59e0b, count: 16, screenShake: 0.14 },
  },
  gull_egg_bomb: {
    kind: "gull_egg_bomb",
    archetype: "bomb",
    dimensions: { radius: 0.16, glowScale: 1.2 },
    colors: { core: 0xfef08a, glow: 0xfbbf24, accent: 0xeab308 },
    flight: { orientToHeading: false, trailType: "dust", trailInterval: 0.06 },
    launch: { muzzleFlash: false },
    impact: { wallType: "burst", color: 0xfbbf24, count: 12 },
  },
  gull_mini_bomb: {
    kind: "gull_mini_bomb",
    archetype: "bomb",
    dimensions: { radius: 0.10, glowScale: 1.2 },
    colors: { core: 0xfbbf24, glow: 0xf59e0b, accent: 0xd97706 },
    flight: { orientToHeading: false, trailType: "dust", trailInterval: 0.06 },
    launch: { muzzleFlash: false },
    impact: { wallType: "burst", color: 0xf59e0b, count: 8 },
  },
  water_mortar: {
    kind: "water_mortar",
    archetype: "bomb",
    dimensions: { radius: 0.16, glowScale: 1.3 },
    colors: { core: 0x0284c7, glow: 0x38bdf8, accent: 0x0369a1 },
    flight: { orientToHeading: false, trailType: "stream", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "splash", color: 0x0284c7, count: 16, floorDecal: "slick" },
  },
  flashbang: {
    kind: "flashbang",
    archetype: "bomb",
    dimensions: { radius: 0.12, glowScale: 1.4 },
    colors: { core: 0x94a3b8, glow: 0xffffff, accent: 0x475569 },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 12 },
    launch: { muzzleFlash: false },
    impact: { wallType: "detonate", color: 0xffffff, count: 20, screenShake: 0.2 },
  },

  // ── 7. Condiments & Food ──────────────────────────────────────────────────
  mustard_glob: {
    kind: "mustard_glob",
    archetype: "condiment",
    dimensions: { radius: 0.14, glowScale: 1.25 },
    colors: { core: 0xfacc15, glow: 0xeab308, accent: 0xffffff },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 12, trailType: "sparks", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "splash", color: 0xfacc15, count: 8, floorDecal: "mustard" },
  },
  ketchup_glob: {
    kind: "ketchup_glob",
    archetype: "condiment",
    dimensions: { radius: 0.14, glowScale: 1.25 },
    colors: { core: 0xb91c1c, glow: 0xdc2626, accent: 0xffffff },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 12, trailType: "sparks", trailInterval: 0.04, trailCount: 1 },
    launch: { muzzleFlash: false },
    impact: { wallType: "splash", color: 0xb91c1c, count: 8, floorDecal: "ketchup" },
  },
  burger_tomato: {
    kind: "burger_tomato",
    archetype: "condiment",
    dimensions: { radius: 0.17, glowScale: 1.15 },
    colors: { core: 0xdc2626, glow: 0xef4444, accent: 0x991b1b },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 20 },
    launch: { muzzleFlash: false },
    impact: { wallType: "burst", color: 0xdc2626, count: 8 },
  },
  burger_lettuce: {
    kind: "burger_lettuce",
    archetype: "condiment",
    dimensions: { radius: 0.16, glowScale: 1.15 },
    colors: { core: 0x16a34a, glow: 0x22c55e, accent: 0x15803d },
    flight: { orientToHeading: false, spinAxis: "roll", spinSpeed: 8 },
    launch: { muzzleFlash: false },
    impact: { wallType: "burst", color: 0x16a34a, count: 6 },
  },
  burger_sauce: {
    kind: "burger_sauce",
    archetype: "condiment",
    dimensions: { radius: 0.13, glowScale: 1.25 },
    colors: { core: 0xeab308, glow: 0xfacc15, accent: 0xffffff },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 10 },
    launch: { muzzleFlash: false },
    impact: { wallType: "burst", color: 0xeab308, count: 8 },
  },
  fry_dart: {
    kind: "fry_dart",
    archetype: "condiment",
    dimensions: { radius: 0.06, length: 0.28, glowScale: 1.3 },
    colors: { core: 0xfacc15, glow: 0xfde047, accent: 0xd97706 },
    flight: { orientToHeading: true, spinAxis: "roll", spinSpeed: 15 },
    launch: { muzzleFlash: false, sparkCount: 6 },
    impact: { wallType: "burst", color: 0xfacc15, count: 8 },
  },
  pearl: {
    kind: "pearl",
    archetype: "condiment",
    dimensions: { radius: 0.15, glowScale: 1.35 },
    colors: { core: 0xf8fafc, glow: 0x38bdf8, accent: 0xffffff },
    flight: { orientToHeading: false, pulseGlow: true },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0x38bdf8, count: 6 },
  },
  fishing_hook: {
    kind: "fishing_hook",
    archetype: "blade",
    dimensions: { radius: 0.08, length: 0.25, glowScale: 1.2 },
    colors: { core: 0x94a3b8, glow: 0xcbd5e1, accent: 0x475569 },
    flight: { orientToHeading: true },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0x94a3b8, count: 6 },
  },
  ornament: {
    kind: "ornament",
    archetype: "bomb",
    dimensions: { radius: 0.16, glowScale: 1.3 },
    colors: { core: 0xef4444, glow: 0xfacc15, accent: 0xfacc15 },
    flight: { orientToHeading: false, pulseGlow: true },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0xef4444, count: 8 },
  },
  timber: {
    kind: "timber",
    archetype: "blade",
    dimensions: { radius: 0.14, length: 0.45, glowScale: 1.15 },
    colors: { core: 0x78350f, glow: 0x92400e, accent: 0x451a03 },
    flight: { orientToHeading: false, spinAxis: "y", spinSpeed: 7 },
    launch: { muzzleFlash: false },
    impact: { wallType: "sparks", color: 0x92400e, count: 6 },
  },
};

/**
 * Resolves a ProjectileVfxConfig by kind, falling back to a sensible default.
 */
export function getProjectileVfxConfig(kind: string): ProjectileVfxConfig {
  return PROJECTILE_VFX_CONFIGS[kind] ?? PROJECTILE_VFX_CONFIGS.bullet;
}
