//! Seeded PRNG — port of `legacy/src/utils/rng.ts`.
//!
//! One canonical implementation, so a seed means the same stream everywhere:
//! the maze generator regenerates a floor exactly from its seed, and the golden
//! fixtures exported from the TS game only mean anything if this stream matches
//! the JS `mulberry32` bit-for-bit. The unit tests pin it against values
//! generated by the legacy implementation.
//!
//! PORTS: `legacy/src/utils/rng.ts`

/// Mulberry32 — fast 32-bit seeded PRNG, uniform in [0, 1).
///
/// Faithful port of the JS version: `Math.imul` → `wrapping_mul`, `>>>` → `>>`
/// on u32, the `(t + imul(...)) ^ t` float-add-then-ToInt32 → `wrapping_add`
/// (the JS sum is exact below 2^53, so ToInt32 reduces it mod 2^32 — identical
/// to a wrapping add).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Mulberry32 {
    a: u32,
}

impl Mulberry32 {
    pub fn new(seed: u32) -> Self {
        Self { a: seed }
    }

    /// Next value in [0, 1). Matches JS `mulberry32(seed)()` exactly: the u32
    /// output divided by 2^32 is exactly representable in f64.
    pub fn next_f64(&mut self) -> f64 {
        self.a = self.a.wrapping_add(0x6d2b_79f5);
        let a = self.a;
        let mut t = (a ^ (a >> 15)).wrapping_mul(1 | a);
        t = t.wrapping_add((t ^ (t >> 7)).wrapping_mul(61 | t)) ^ t;
        f64::from(t ^ (t >> 14)) / 4_294_967_296.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Golden values generated from legacy/src/utils/rng.ts (node, 2026-08-09).
    /// If this test fails, the sim can never replay a TS fixture — fix the RNG,
    /// never the pins.
    #[test]
    fn matches_js_oracle() {
        let cases: &[(u32, [f64; 5])] = &[
            (
                0,
                [
                    0.26642920868471265,
                    0.0003297457005828619,
                    0.2232720274478197,
                    0.1462021479383111,
                    0.46732782293111086,
                ],
            ),
            (
                1,
                [
                    0.6270739405881613,
                    0.002735721180215478,
                    0.5274470399599522,
                    0.9810509674716741,
                    0.9683778982143849,
                ],
            ),
            (
                7,
                [
                    0.011704753153026104,
                    0.06195825757458806,
                    0.97690763277933,
                    0.6990287057124078,
                    0.5214452685322613,
                ],
            ),
            (
                123_456_789,
                [
                    0.2577907438389957,
                    0.9707721115555614,
                    0.7853280142880976,
                    0.20616457983851433,
                    0.30307188746519387,
                ],
            ),
            (
                u32::MAX,
                [
                    0.8964226141106337,
                    0.189478256739676,
                    0.7156526781618595,
                    0.9440599093213677,
                    0.8452364315744489,
                ],
            ),
        ];
        for &(seed, expected) in cases {
            let mut rng = Mulberry32::new(seed);
            for (i, &want) in expected.iter().enumerate() {
                let got = rng.next_f64();
                assert!(
                    got == want,
                    "seed {seed} draw {i}: got {got:?}, want {want:?} (bit-exact required)"
                );
            }
        }
    }
}
