/**
 * THE DESCENT SCREEN — shown while the next floor is built.
 *
 * ── THE ONE THING THIS SCREEN MUST NOT DO ──
 * Stall. It exists because building a floor blocks the GPU, and its entire job
 * is to be on screen DURING that block. That makes it the one place in this
 * migration where "the UI is painted from the render loop" is a hazard rather
 * than a convenience: if the loop is stalled, a painted screen freezes with it,
 * whereas the DOM version was composited by the browser and kept animating.
 *
 * So the bar is driven by WALL CLOCK, not by frames. When the loop stutters the
 * bar jumps to where it should be rather than pausing mid-sweep — a bar that
 * stops moving reads as a hang, which is exactly the impression this screen
 * exists to prevent. `descent bar stall is one compile` is a lesson this repo
 * has already paid for once.
 *
 * ── WHY THE MAZE ON SCREEN IS NOT THE REAL ONE ──
 * It would be easy to draw `state.grid` here — the floor is fully generated by
 * the time the bar is moving, and `map-render.ts` already knows how. It would
 * also hand the player the finished map of a floor they are about to explore,
 * which is the exact spoiler the fog exists to prevent (`startLevel` resets fog
 * every descent for this reason). So this grows its OWN throwaway labyrinth in
 * the same visual language — the track-first circuit look, gold arteries on
 * cold stone — and the player learns nothing from studying it.
 *
 * The first canvas port of this screen dropped the labyrinth, the caption, the
 * divider and the percentage, keeping only a title and a bar on a flat black
 * field. That was not a stylistic simplification: the screen had nothing left
 * on it, which on the one screen whose whole job is to say "something is
 * happening" is the worst available failure. All of it is back.
 */
import { UI, GRID, C } from "../theme";
import { fillRect, rect, strokeRect, text, type UiFrame } from "../im";
import { close, push, type UiScreen } from "../stack";

/**
 * The SAME contract `floor-loading.ts` publishes, so the two are drop-in
 * interchangeable and the caller never learns which one it got.
 *
 * `phase()` NEVER goes backwards — the DOM version clamped that and it matters:
 * a bar that retreats mid-descent reads as the load having failed and restarted.
 */
export interface FloorLoading {
  phase(label: string, frac: number): void;
  close(): void;
}

/**
 * The box this screen is authored for — see `UiScreen.design`.
 *
 * Deliberately the smallest in the game. There are four lines on it and no
 * lists, so it can afford the largest zoom the grid allows, and it is the one
 * screen a player stares at with nothing else to do. On a 1600x900 grid this
 * resolves to 3x: depth numerals 72 texels tall instead of 24.
 */
export const DESIGN = { w: 480, h: 270, max: 3 };

/** Cell states in the throwaway labyrinth drawn behind the bar. */
const WALL = 0;
const FLOOR_ = 1;
const ARTERY = 2;

/** UI pixels per labyrinth cell. Whole, so the cells land on the pixel grid. */
const CELL = 8;

interface Cell {
  x: number;
  y: number;
}

/**
 * Grow a decorative labyrinth with a wide gold "artery" threaded through it —
 * the same shape language as a real floor (a circuit the maze fills in around)
 * without being any actual floor. Deliberately unseeded: this is decoration,
 * and a different pattern every descent reads as a different place.
 *
 * `rand` is injectable ONLY so the shape can be asserted from a test without a
 * renderer; the game always uses `Math.random`.
 */
export function growLabyrinth(w: number, h: number, rand: () => number = Math.random): Uint8Array {
  const g = new Uint8Array(Math.max(0, w * h)); // all WALL
  if (w < 5 || h < 5) return g;
  const at = (x: number, y: number): number => y * w + x;
  const inside = (x: number, y: number): boolean => x > 0 && y > 0 && x < w - 1 && y < h - 1;

  // ── Growing-tree maze on odd cells (the surround) ──
  const stack: Cell[] = [];
  const start = { x: 1, y: 1 };
  g[at(start.x, start.y)] = FLOOR_;
  stack.push(start);
  const DIRS = [
    [2, 0],
    [-2, 0],
    [0, 2],
    [0, -2],
  ] as const;
  while (stack.length) {
    // Mostly depth-first (long corridors), sometimes random (junctions).
    const i = rand() < 0.7 ? stack.length - 1 : (rand() * stack.length) | 0;
    const c = stack[i];
    const opts = DIRS.filter(([dx, dy]) => inside(c.x + dx, c.y + dy) && g[at(c.x + dx, c.y + dy)] === WALL);
    if (!opts.length) {
      stack.splice(i, 1);
      continue;
    }
    const [dx, dy] = opts[(rand() * opts.length) | 0];
    g[at(c.x + dx / 2, c.y + dy / 2)] = FLOOR_;
    g[at(c.x + dx, c.y + dy)] = FLOOR_;
    stack.push({ x: c.x + dx, y: c.y + dy });
  }

  // ── The artery: a fat wandering loop carved over the top, so the eye has a
  //    through-line to follow while the bar fills. Two horizontal runs joined
  //    at the ends, wobbled vertically — reads as a circuit, not a corridor. ──
  const carve = (x: number, y: number): void => {
    for (let oy = -1; oy <= 1; oy++) {
      for (let ox = -1; ox <= 1; ox++) {
        if (inside(x + ox, y + oy)) g[at(x + ox, y + oy)] = ARTERY;
      }
    }
  };
  const yTop = Math.floor(h * 0.3);
  const yBot = Math.floor(h * 0.72);
  let y = yTop;
  for (let x = 2; x < w - 2; x++) {
    if (rand() < 0.18) y += rand() < 0.5 ? 1 : -1;
    y = Math.max(2, Math.min(h - 3, y));
    carve(x, y);
  }
  for (let yy = yTop; yy <= yBot; yy++) carve(w - 3, yy);
  y = yBot;
  for (let x = w - 3; x > 2; x--) {
    if (rand() < 0.18) y += rand() < 0.5 ? 1 : -1;
    y = Math.max(2, Math.min(h - 3, y));
    carve(x, y);
  }
  for (let yy = yTop; yy <= yBot; yy++) carve(2, yy);
  return g;
}

interface LoadState {
  level: number;
  progress: number;
  label: string;
  startedAt: number;
  cols: number;
  rows: number;
  maze: Uint8Array;
}

let live: LoadState | null = null;

export function isFloorLoadingOpen(): boolean {
  return live !== null;
}

/**
 * Grow the labyrinth on the FIRST PAINT, and again only if the cell count
 * changes.
 *
 * Not at `open()`: the caller is the descent path, which knows the floor number
 * and nothing about how big the frame is. The frame size (and therefore the
 * zoom, and therefore the cell count) is first knowable inside `paint`.
 */
function ensureMaze(s: LoadState, f: UiFrame): void {
  const cols = Math.ceil(f.w / CELL) + 1;
  const rows = Math.ceil(f.h / CELL) + 1;
  if (cols === s.cols && rows === s.rows) return;
  s.cols = cols;
  s.rows = rows;
  s.maze = growLabyrinth(cols, rows);
}

/**
 * The whole labyrinth is laid out from the first frame, in cold unlit stone,
 * and the progress sweep ENERGISES it left to right. Revealing the tiles
 * themselves instead left half the screen empty black for half the descent,
 * which reads as "nothing is happening" — the opposite of what a loading screen
 * is for.
 */
function paintLabyrinth(f: UiFrame, s: LoadState, frac: number, t: number): void {
  const g = f.g;
  const edge = frac * (s.cols + 8);
  for (let j = 0; j < s.rows; j++) {
    for (let i = 0; i < s.cols; i++) {
      const kind = s.maze[j * s.cols + i];
      if (kind === WALL) continue;
      const d = edge - i; // >0 once the sweep has passed this column
      const lit = Math.max(0, Math.min(1, d / 6));
      const x = i * CELL;
      const y = j * CELL;
      if (kind === ARTERY) {
        // The gold through-line, with a travelling pulse once it is live.
        const pulse = 0.55 + 0.45 * Math.sin(t * 3 - i * 0.35);
        g.fillStyle = `rgba(240,166,60,${(0.1 + (0.12 + 0.5 * pulse) * lit).toFixed(3)})`;
      } else {
        g.fillStyle = `rgba(26,31,43,${(0.34 + 0.61 * lit).toFixed(3)})`;
      }
      g.fillRect(x, y, CELL - 1, CELL - 1);
      // A cold rim rides the leading edge — tiles snapping into place.
      if (d > 0 && d < 6 && kind !== ARTERY) {
        g.fillStyle = `rgba(111,208,232,${(0.5 * (1 - d / 6)).toFixed(3)})`;
        g.fillRect(x, y, CELL - 1, 1);
      }
    }
  }
}

/** The gold rule with a diamond at its centre, under the depth numeral. */
function divider(f: UiFrame, cx: number, y: number, half: number): void {
  fillRect(f, rect(cx - half, y, half - 8, 1), UI.sheetEdge);
  fillRect(f, rect(cx + 8, y, half - 8, 1), UI.sheetEdge);
  fillRect(f, rect(cx - 2, y - 2, 5, 5), UI.gold);
}

export function openFloorLoading(level: number): FloorLoading {
  live = {
    level,
    progress: 0,
    label: "WAKING THE STONE",
    startedAt: performance.now(),
    cols: 0,
    rows: 0,
    maze: new Uint8Array(0),
  };
  const screen: UiScreen = {
    id: "floor-loading",
    // Pauses, but nothing is running underneath anyway — the sim is between
    // floors. The flag matters so a stray key cannot act on the old floor.
    pauses: true,
    focus: 0,
    scroll: 0,
    design: DESIGN,
    // Not dismissable: closing it would reveal a half-built floor.
    onCancel: () => true,
    onClose: () => {
      live = null;
    },
    paint(f) {
      const s = live;
      if (!s) return;
      ensureMaze(s, f);

      // MAX of reported progress and a slow wall-clock creep. If the build
      // blocks the loop, the reported value stops arriving; the creep keeps the
      // bar honest-looking without ever overtaking real progress by much.
      const elapsed = performance.now() - s.startedAt;
      const creep = Math.min(0.9, elapsed / 4000);
      const frac = Math.max(s.progress, creep);

      // Opaque, not a scrim: what is behind this is a half-built floor and it
      // must not show through.
      fillRect(f, rect(0, 0, f.w, f.h), C(0));
      paintLabyrinth(f, s, frac, elapsed / 1000);

      // A flat dim over the whole field rather than a radial vignette. A smooth
      // ramp gets quantized to 32 colours downstream and bands anyway, so the
      // banding may as well not be there at all.
      f.g.fillStyle = "rgba(0,0,0,0.5)";
      f.g.fillRect(0, 0, f.w, f.h);

      const cx = Math.round(f.w / 2);
      const top = Math.round(f.h / 2) - 56;

      text(f, "DESCENDING", cx, top, { size: 8, colour: UI.gold, align: "center" });
      text(f, `DEPTH ${s.level}`, cx, top + 20, { size: 24, colour: UI.text, align: "center" });
      divider(f, cx, top + 58, 96);
      text(f, s.label.toUpperCase(), cx, top + 70, { size: 8, colour: UI.arcane, align: "center" });

      // The bar reads as an instrument: a sunken well, a 2px frame, and the
      // fill inset inside it so the frame is never overdrawn.
      const track = rect(cx - 128, top + 90, 256, 14);
      fillRect(f, track, UI.well);
      strokeRect(f, track, UI.sheetEdge, 2);
      const fillW = Math.round((track.w - 4) * Math.max(0, Math.min(1, frac)));
      if (fillW > 0) fillRect(f, rect(track.x + 2, track.y + 2, fillW, track.h - 4), UI.gold);
      // A lit leading edge, so the bar still has a head when it is barely moving.
      if (fillW > 2) fillRect(f, rect(track.x + fillW, track.y + 2, 2, track.h - 4), UI.heading);

      text(f, `${Math.round(frac * 100)}%`, cx, track.y + track.h + GRID, {
        size: 8,
        colour: UI.textDim,
        align: "center",
      });
    },
  };
  push(screen);

  return {
    phase(label, frac) {
      if (!live) return;
      live.label = label;
      // Monotonic, like the DOM version: never let the bar retreat.
      live.progress = Math.max(live.progress, Math.max(0, Math.min(1, frac)));
    },
    close() {
      close("floor-loading");
    },
  };
}
