//! Embed the baked GUI icons — `assets/gui/icons/*.png`, produced by
//! `legacy/scripts/bake-gui-icons.mjs`.
//!
//! WHY GENERATED. The alternative is 51 hand-written `include_bytes!` lines,
//! and the failure mode of that list is a silent one: the bake gains an item,
//! nobody adds the line, and the counter that draws it shows a hole months
//! later. The generated table cannot forget a file.
//!
//! WHY IT IS STILL GATED. A generated catalog is a cache with no invalidation
//! unless something checks it — so `icons.rs` compares these names against the
//! `files` list in the bake's own `icons.json`, which this build script does not
//! read. Two independent derivations of the same set; a mismatch is a test
//! failure, not a hole in a menu.
//!
//! `rerun-if-changed` on the DIRECTORY as well as the manifest: cargo only
//! re-runs a build script when a watched path's mtime moves, and a new PNG
//! changes the directory's.
//!
//! PORTS-NOTHING — Cargo build script

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    // Two bakes, one shape: `assets/gui/<dir>/*.png` → a `(name, bytes)` table.
    // The card faces are a SEPARATE bake from the icons and deliberately so —
    // a card is `cardFaceAt()`, a different renderer at a different aspect, and
    // it ships two sizes and two finishes per card. Same embedding rules apply.
    embed("icons", "icons_embed.rs");
    embed("cards", "cards_embed.rs");
}

/// Scan `assets/gui/<name>` and write a `(stem, bytes)` table to `$OUT_DIR/<dest>`.
fn embed(name: &str, dest_file: &str) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(format!("../../assets/gui/{name}"));
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.extension().and_then(|s| s.to_str()) != Some("png") {
                continue;
            }
            let Some(stem) = p.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            println!("cargo:rerun-if-changed={}", p.display());
            names.push(stem.to_string());
        }
    }
    // Sorted, so the table's order is a property of the SET and not of the
    // filesystem's readdir order — otherwise the generated file churns.
    names.sort();

    let mut out = format!(
        "// @generated by build.rs from assets/gui/{name} — do not edit.\n\
         pub static EMBEDDED: &[(&str, &[u8])] = &[\n"
    );
    for n in &names {
        let _ = writeln!(
            out,
            "    ({n:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../assets/gui/{name}/{n}.png\"))),"
        );
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join(dest_file);
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {dest_file}: {e}"));
}
