/**
 * 📦 Manifest Inventory — Authored sheet facings registry.
 *
 * Eliminates blind HTTP 404 network probes for directions that were never authored.
 */
import type { Dir } from "../engine/render/paint-types";

export const IMPORTED_FACINGS: Record<string, readonly Dir[]> = {
  archivist: ["S"],
  bat: ["S"],
  beaver: ["E", "S"],
  bloater: ["S"],
  broodmother: ["S"],
  brute: ["S"],
  burger: ["S"],
  chomper: ["S"],
  cigarette: ["S"],
  clockwork_knight_football: ["E", "N", "S"],
  clockwork_knight_baseball: ["E", "N", "S"],
  clockwork_knight: ["E", "N", "S"],
  compass: ["E", "N", "S"],
  crawler: ["S"],
  crawling_hand: ["S"],
  croaker: ["S"],
  crystalback: ["S"],
  demon: ["S"],
  dragon: ["S"],
  dragon_snake_head: ["S"],
  dragon_snake_body: ["S"],
  dragon_snake_tail: ["S"],
  espresso: ["S"],
  fish_feet: ["E", "S"],
  fries: ["E", "N", "S"],
  frog: ["E", "S"],
  ghost: ["S"],
  gnome: ["S"],
  goblin: ["S"],
  golem: ["S"],
  hound: ["S"],
  jade_buddha: ["S"],
  jester: ["S"],
  magnet: ["S"],
  mario: ["N", "S"],
  merchant: ["S"],
  mimic: ["S"],
  milkshake: ["E", "N", "S"],
  necro: ["S"],
  overlord: ["S"],
  pin: ["S"],
  pinball_knight: ["E", "N", "S"],
  platypus: ["S"],
  reaper: ["S"],
  slime: ["E", "N", "S"],
  spider: ["S"],
  sporeling: ["S"],
  sumo_ninja: ["S"],
  stiltneck: ["E", "S"],
  warden: ["S"],
  webspinner: ["S"],
  trex: ["S"],
  toucan: ["S"],
  zippo: ["S"],
  gas_can: ["S"],
  christmas_tree: ["S"],
  hamster_ball: ["S"],
  ascii_human: ["S"],
  computer_screen: ["S"],
  giant_ascii_human: ["S"],
  cerberus: ["S"],
  clam: ["S"],
  crab: ["S"],
  pinball_boss: ["E", "N", "S"],
  medusa: ["S"],
  dracula: ["S"],
  spinning_top: ["S"],
  shark_trapper: ["S"],
  dolphin_brawler: ["S"],
  octopus_gunner: ["S"],
  clownfish_mob: ["S"],
  lionfish_mob: ["S"],
  anglerfish_mob: ["S"],
  pufferfish_mob: ["S"],
  swordfish_mob: ["S"],
  moray_mob: ["S"],
  seahorse_mob: ["S"],
  zombie: ["E"],
  maze_merchant: ["S"],
  tavern_smith: ["S"],
  tavern_alchemist: ["S"],
  tavern_dealer: ["S"],
  tavern_armorer: ["S"],
  tavern_gambler: ["S"],
  doppelganger: ["S"],
  pit_peeper: ["S"],
  dumpster_dan: ["S"],
  toaster_gremlin: ["S"],
  lip_flapper: ["S"],
  blaster_frank: ["E", "N", "S"],
  junkbot: ["S"],
  junkbot_tractor: ["S"],
  junkbot_cyber: ["S"],
  junkbot_motor: ["S"],
  junkbot_crane: ["S"],
  junkbot_appliance: ["S"],
  corvid_bomber: ["S"],
  vulture_scavenger: ["S"],
  gull_bomber: ["S"],
  sky_falcon: ["S"],
  magma_slime: ["S"],
  toxic_slime: ["S"],
  frost_slime: ["S"],
  void_slime: ["S"],
  riot_cop: ["S"],
  highway_patrol: ["S"],
  detective_cop: ["S"],
  robo_cop: ["S"],
  hotdog: ["S"],
};

export function hasAuthoredFacing(name: string, dir: Dir): boolean {
  const facings = IMPORTED_FACINGS[name];
  if (!facings) return dir === "S";
  return facings.includes(dir);
}

export function authoredFacingsFor(name: string): readonly Dir[] {
  return IMPORTED_FACINGS[name] ?? ["S"];
}
