//! The legacy immediate-mode GUI, ported 1:1 from `legacy/src/game/pinball-knight/gui/`.
//!
//! PORTS: `gui/im.ts`, `gui/input.ts`, `gui/touch.ts`, `gui/layer.ts`, `legacy/src/pixel/pixel-canvas.ts`, `render/remote-party.ts`, `boot/warmup.ts`, `render/arc-lanes.ts`, `render/arc-kickers.ts`, `render/light-crossing.ts`, `render/aim-indicator.ts`, `legacy/src/pixel/pixel-icon.ts`, `render/palette-shading.ts`, `render/monster-portrait.ts`, `legacy/src/pixel/pixel-text.ts`, `gui/coords.ts`, `ui.ts`, `legacy/src/pixel/pixel-font.ts`, `hud.ts`, `map-overlay.ts`, `hud-meter.ts`, `gui/apply-settings.ts`, `pickup-toast.ts`, `gui/globe-ripple.ts`, `floor-loading.ts`, `pixel-fonts.ts`, `dev/gui-hooks.ts`, `engine/render/sprite.ts`

pub mod apply_settings;
pub mod boot;
pub mod cards;
pub mod coords;
pub mod dev_gui_hooks;
pub mod engine;
pub mod floor_loading;
pub mod font;
pub mod globe_ripple;
pub mod hud_ctrl;
pub mod hud_meter;
pub mod icons;
pub mod im;
pub mod input;
pub mod layer;
pub mod map_overlay;
pub mod painter;
pub mod palette;
pub mod pickup_toast;
pub mod pixel_canvas;
pub mod pixel_font;
pub mod pixel_fonts;
pub mod pixel_icon;
pub mod pixel_text;
pub mod remote_party;
pub mod render;
pub mod root;
pub mod screens;
pub mod stack;
pub mod theme;
pub mod touch;
pub mod ui_shim;

pub use apply_settings::*;
pub use boot::*;
pub use coords::*;
pub use dev_gui_hooks::*;
pub use engine::*;
pub use floor_loading::*;
pub use font::Fonts;
pub use globe_ripple::*;
pub use hud_ctrl::*;
pub use hud_meter::*;
pub use im::{Rect, UiFrame, UiInput};
pub use input::*;
pub use layer::*;
pub use map_overlay::*;
pub use painter::{Painter, Rgba};
pub use pickup_toast::*;
pub use pixel_canvas::*;
pub use pixel_font::*;
pub use pixel_fonts::*;
pub use pixel_icon::*;
pub use pixel_text::*;
pub use remote_party::*;
pub use render::*;
pub use stack::{ScreenEntry, UiStack};
pub use touch::*;
